name: auto_label

on:
  pull_request:
    types: [opened]

permissions:
  contents: write
  pull-requests: write

jobs:
  Determine-Workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Label Pull Request
      uses: actions/labeler@v5

